// TODO: refactor to for loop

dataset = [
        // central switch
        { data: { id: 'mainLan', label: 'switch' }, classes: 'switch' },

        // group 1
        { data: { id: 'ispA'}},
        { data: { id: 'anode-0', label: '172.30.7.4', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-1', label: '172.30.7.5', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-2', label: '172.30.7.6', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-3', label: '172.30.7.7', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-4', label: '172.30.7.8', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-5', label: '172.30.7.9', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-6', label: '172.30.7.10', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-7', label: '172.30.7.11', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-8', label: '172.30.7.12, 172.30.4.2', parent: 'ispA', numPorts: 2}},
        { data: { id: 'anode-9', label: '172.30.7.13, 172.30.5.2', parent: 'ispA', numPorts: 2}},
        { data: { id: 'anode-10', label: '172.30.7.14', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-11', label: '172.30.7.15', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-12', label: '172.30.7.16', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-13', label: '172.30.7.17', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-14', label: '172.30.7.18', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-15', label: '172.30.7.19', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-16', label: '172.30.7.20', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-17', label: '172.30.7.21', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-18', label: '172.30.7.22', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-19', label: '172.30.7.23', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-20', label: '172.30.7.24', parent: 'ispA', numPorts: 1}},
        { data: { id: 'anode-21', label: '172.30.7.25', parent: 'ispA', numPorts: 1}},
        { data: { id: 'nodeC01', label: '172.30.7.3, 172.30.2.5', parent: 'ispA', numPorts: 2}},
        { data: { id: 'nodeC1', label: '172.30.7.2, 172.30.2.2', parent: 'ispA', numPorts: 2 }},
        { data: { id: 'lanC1', label: 'switch', parent: 'ispA', numPorts: 24}, classes: 'switch'},

        // group 2
        { data: { id: 'ispB'}},
        { data: { id: 'bnode-0', label: '172.30.3.4', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-1', label: '172.30.3.5', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-2', label: '172.30.3.6', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-3', label: '172.30.3.7', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-4', label: '172.30.3.8', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-5', label: '172.30.3.9', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-6', label: '172.30.3.10', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-7', label: '172.30.3.11', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-8', label: '172.30.3.12, 172.30.1.2', parent: 'ispB', numPorts: 2 }},
        { data: { id: 'bnode-9', label: '172.30.3.13, 172.30.5.3', parent: 'ispB', numPorts: 2 }},
        { data: { id: 'bnode-10', label: '172.30.3.14', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-11', label: '172.30.3.15', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-12', label: '172.30.3.16', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-13', label: '172.30.3.17', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-14', label: '172.30.3.18', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-15', label: '172.30.3.19', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-16', label: '172.30.3.20', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-17', label: '172.30.3.21', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-18', label: '172.30.3.22', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-19', label: '172.30.3.21', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-20', label: '172.30.3.22', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'bnode-21', label: '172.30.3.23', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'nodeC02', label: '172.30.3.3, 172.30.2.6', parent: 'ispB', numPorts: 2}},
        { data: { id: 'nodeC2', label: '172.30.3.2, 172.30.2.3', parent: 'ispB', numPorts: 2}},
        { data: { id: 'lanC2', label: 'switch', parent: 'ispB', numPorts: 24 }, classes: 'switch' },

        // group 3
        { data: { id: 'ispC'}},
        { data: { id: 'dnode-3', label: '172.30.6.4', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-4', label: '172.30.6.5', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-5', label: '172.30.6.6', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-6', label: '172.30.6.7', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-7', label: '172.30.6.8', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-8', label: '172.30.6.9, 172.30.1.3', parent: 'ispC', numPorts: 2  }},
        { data: { id: 'dnode-9', label: '172.30.6.10, 172.30.4.3', parent: 'ispC', numPorts: 2  }},
        { data: { id: 'dnode-10', label: '172.30.6.11', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-12', label: '172.30.6.12', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-13', label: '172.30.6.13', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-14', label: '172.30.6.14', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-15', label: '172.30.6.15', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-16', label: '172.30.6.16', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-17', label: '172.30.6.17', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-18', label: '172.30.6.18', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-19', label: '172.30.6.19', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-20', label: '172.30.6.20', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'dnode-21', label: '172.30.6.21', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'nodeC04', label: '172.30.6.3, 172.30.2.7', parent: 'ispC', numPorts: 2  }},
        { data: { id: 'nodeC4', label: '172.30.6.2, 172.30.2.4', parent: 'ispC', numPorts: 2  }},
        { data: { id: 'lanC4', label: 'switch', parent: 'ispC', numPorts: 20 }, classes: 'switch' },
        
        // edges for group 1
        { data: { id: 'eanode-0', source: 'anode-0', target: 'lanC1', sPort: 0, tPort: 0 }, classes: 'dashed' },
        { data: { id: 'eanode-1', source: 'anode-1', target: 'lanC1', sPort: 0, tPort: 1 }, classes: 'dashed' },
        { data: { id: 'eanode-2', source: 'anode-2', target: 'lanC1', sPort: 0, tPort: 2 }, classes: 'dashed' },
        { data: { id: 'eanode-3', source: 'anode-3', target: 'lanC1', sPort: 0, tPort: 3 }, classes: 'dashed' },
        { data: { id: 'eanode-4', source: 'anode-4', target: 'lanC1', sPort: 0, tPort: 4 }, classes: 'dashed' },
        { data: { id: 'eanode-5', source: 'anode-5', target: 'lanC1', sPort: 0, tPort: 5 }, classes: 'dashed' },
        { data: { id: 'eanode-6', source: 'anode-6', target: 'lanC1', sPort: 0, tPort: 6 }, classes: 'dashed' },
        { data: { id: 'eanode-7', source: 'anode-7', target: 'lanC1', sPort: 0, tPort: 7 }, classes: 'dashed' },
        { data: { id: 'eanode-8', source: 'anode-8', target: 'lanC1', sPort: 0, tPort: 8 }, classes: 'dashed' },
        { data: { id: 'eanode-9', source: 'anode-9', target: 'lanC1', sPort: 0, tPort: 9 }, classes: 'dashed' },
        { data: { id: 'eanode-10', source: 'anode-10', target: 'lanC1', sPort: 0, tPort: 10 }, classes: 'dashed' },
        { data: { id: 'eanode-11', source: 'anode-11', target: 'lanC1', sPort: 0, tPort: 11 }, classes: 'dashed' },
        { data: { id: 'eanode-12', source: 'anode-12', target: 'lanC1', sPort: 0, tPort: 12 }, classes: 'dashed' },
        { data: { id: 'eanode-13', source: 'anode-13', target: 'lanC1', sPort: 0, tPort: 13 }, classes: 'dashed' },
        { data: { id: 'eanode-14', source: 'anode-14', target: 'lanC1', sPort: 0, tPort: 14 }, classes: 'dashed' },
        { data: { id: 'eanode-15', source: 'anode-15', target: 'lanC1', sPort: 0, tPort: 15 }, classes: 'dashed' },
        { data: { id: 'eanode-16', source: 'anode-16', target: 'lanC1', sPort: 0, tPort: 16 }, classes: 'dashed' },
        { data: { id: 'eanode-17', source: 'anode-17', target: 'lanC1', sPort: 0, tPort: 17 }, classes: 'dashed' },
        { data: { id: 'eanode-18', source: 'anode-18', target: 'lanC1', sPort: 0, tPort: 18 }, classes: 'dashed' },
        { data: { id: 'eanode-19', source: 'anode-19', target: 'lanC1', sPort: 0, tPort: 19 }, classes: 'dashed' },
        { data: { id: 'eanode-20', source: 'anode-20', target: 'lanC1', sPort: 0, tPort: 20 }, classes: 'dashed' },
        { data: { id: 'eanode-21', source: 'anode-21', target: 'lanC1', sPort: 0, tPort: 21 }, classes: 'dashed' },
        { data: { id: 'enodeC01', source: 'nodeC01', target: 'lanC1', sPort: 0, tPort: 22 }, classes: 'dashed' },
        { data: { id: 'enodeC1', source: 'nodeC1', target: 'lanC1', sPort: 0, tPort: 23 }, classes: 'dashed' },

        // edges for group 2
        { data: { id: 'ebnode-0', source: 'bnode-0', target: 'lanC2', sPort: 0, tPort: 0 }, classes: 'dashed' },
        { data: { id: 'ebnode-1', source: 'bnode-1', target: 'lanC2', sPort: 0, tPort: 1 }, classes: 'dashed' },
        { data: { id: 'ebnode-2', source: 'bnode-2', target: 'lanC2', sPort: 0, tPort: 2 }, classes: 'dashed' },
        { data: { id: 'ebnode-3', source: 'bnode-3', target: 'lanC2', sPort: 0, tPort: 3 }, classes: 'dashed' },
        { data: { id: 'ebnode-4', source: 'bnode-4', target: 'lanC2', sPort: 0, tPort: 4 }, classes: 'dashed' },
        { data: { id: 'ebnode-5', source: 'bnode-5', target: 'lanC2', sPort: 0, tPort: 5 }, classes: 'dashed' },
        { data: { id: 'ebnode-6', source: 'bnode-6', target: 'lanC2', sPort: 0, tPort: 6 }, classes: 'dashed' },
        { data: { id: 'ebnode-7', source: 'bnode-7', target: 'lanC2', sPort: 0, tPort: 7 }, classes: 'dashed' },
        { data: { id: 'ebnode-8', source: 'bnode-8', target: 'lanC2', sPort: 0, tPort: 8 }, classes: 'dashed' },
        { data: { id: 'ebnode-9', source: 'bnode-9', target: 'lanC2', sPort: 0, tPort: 9 }, classes: 'dashed' },
        { data: { id: 'ebnode-10', source: 'bnode-10', target: 'lanC2', sPort: 0, tPort: 10 }, classes: 'dashed' },
        { data: { id: 'ebnode-11', source: 'bnode-11', target: 'lanC2', sPort: 0, tPort: 10 }, classes: 'dashed' },
        { data: { id: 'ebnode-12', source: 'bnode-12', target: 'lanC2', sPort: 0, tPort: 11 }, classes: 'dashed' },
        { data: { id: 'ebnode-13', source: 'bnode-13', target: 'lanC2', sPort: 0, tPort: 12 }, classes: 'dashed' },
        { data: { id: 'ebnode-14', source: 'bnode-14', target: 'lanC2', sPort: 0, tPort: 13 }, classes: 'dashed' },
        { data: { id: 'ebnode-15', source: 'bnode-15', target: 'lanC2', sPort: 0, tPort: 14 }, classes: 'dashed' },
        { data: { id: 'ebnode-16', source: 'bnode-16', target: 'lanC2', sPort: 0, tPort: 15 }, classes: 'dashed' },
        { data: { id: 'ebnode-17', source: 'bnode-17', target: 'lanC2', sPort: 0, tPort: 16 }, classes: 'dashed' },
        { data: { id: 'ebnode-18', source: 'bnode-18', target: 'lanC2', sPort: 0, tPort: 17 }, classes: 'dashed' },
        { data: { id: 'ebnode-19', source: 'bnode-19', target: 'lanC2', sPort: 0, tPort: 18 }, classes: 'dashed' },
        { data: { id: 'ebnode-20', source: 'bnode-20', target: 'lanC2', sPort: 0, tPort: 19 }, classes: 'dashed' },
        { data: { id: 'ebnode-21', source: 'bnode-21', target: 'lanC2', sPort: 0, tPort: 20 }, classes: 'dashed' },
        { data: { id: 'enodeC02', source: 'nodeC02', target: 'lanC2', sPort: 0, tPort: 22 }, classes: 'dashed' },
        { data: { id: 'enodeC2', source: 'nodeC2', target: 'lanC2', sPort: 0, tPort: 23 }, classes: 'dashed' },

        // edges for group 3
        { data: { id: 'ednode-3', source: 'dnode-3', target: 'lanC4', sPort: 0, tPort: 0 }, classes: 'dashed' },
        { data: { id: 'ednode-4', source: 'dnode-4', target: 'lanC4', sPort: 0, tPort: 1 }, classes: 'dashed' },
        { data: { id: 'ednode-5', source: 'dnode-5', target: 'lanC4', sPort: 0, tPort: 2 }, classes: 'dashed' },
        { data: { id: 'ednode-6', source: 'dnode-6', target: 'lanC4', sPort: 0, tPort: 3 }, classes: 'dashed' },
        { data: { id: 'ednode-7', source: 'dnode-7', target: 'lanC4', sPort: 0, tPort: 4 }, classes: 'dashed' },
        { data: { id: 'ednode-8', source: 'dnode-8', target: 'lanC4', sPort: 0, tPort: 5 }, classes: 'dashed' },
        { data: { id: 'ednode-9', source: 'dnode-9', target: 'lanC4', sPort: 0, tPort: 6 }, classes: 'dashed' },
        { data: { id: 'ednode-10', source: 'dnode-10', target: 'lanC4', sPort: 0, tPort: 7 }, classes: 'dashed' },
        { data: { id: 'ednode-12', source: 'dnode-12', target: 'lanC4', sPort: 0, tPort: 8 }, classes: 'dashed' },
        { data: { id: 'ednode-13', source: 'dnode-13', target: 'lanC4', sPort: 0, tPort: 9 }, classes: 'dashed' },
        { data: { id: 'ednode-14', source: 'dnode-14', target: 'lanC4', sPort: 0, tPort: 10 }, classes: 'dashed' },
        { data: { id: 'ednode-15', source: 'dnode-15', target: 'lanC4', sPort: 0, tPort: 11 }, classes: 'dashed' },
        { data: { id: 'ednode-16', source: 'dnode-16', target: 'lanC4', sPort: 0, tPort: 12 }, classes: 'dashed' },
        { data: { id: 'ednode-17', source: 'dnode-17', target: 'lanC4', sPort: 0, tPort: 13 }, classes: 'dashed' },
        { data: { id: 'ednode-18', source: 'dnode-18', target: 'lanC4', sPort: 0, tPort: 14 }, classes: 'dashed' },
        { data: { id: 'ednode-19', source: 'dnode-19', target: 'lanC4', sPort: 0, tPort: 15 }, classes: 'dashed' },
        { data: { id: 'ednode-20', source: 'dnode-20', target: 'lanC4', sPort: 0, tPort: 16 }, classes: 'dashed' },
        { data: { id: 'ednode-21', source: 'dnode-21', target: 'lanC4', sPort: 0, tPort: 17 }, classes: 'dashed' },
        { data: { id: 'enodeC04', source: 'nodeC04', target: 'lanC4', sPort: 0, tPort: 18 }, classes: 'dashed' },
        { data: { id: 'enodeC4', source: 'nodeC4', target: 'lanC4', sPort: 0, tPort: 19 }, classes: 'dashed' },

        // edges connnecting two nodes to central switch
        { data: { id: 'enodeC01Main', source: 'nodeC01', target: 'mainLan', sPort: 1, tPort: 0 } },
        { data: { id: 'enodeC1Main', source: 'nodeC1', target: 'mainLan', sPort: 1, tPort: 1 } },
        { data: { id: 'enodeC02Main', source: 'nodeC02', target: 'mainLan', sPort: 1, tPort: 2 } },
        { data: { id: 'enodeC2Main', source: 'nodeC2', target: 'mainLan', sPort: 1, tPort: 3 } },
        { data: { id: 'enodeC04Main', source: 'nodeC04', target: 'mainLan', sPort: 1, tPort: 4 } },
        { data: { id: 'enodeC4Main', source: 'nodeC4', target: 'mainLan', sPort: 1, tPort: 5 } },

        // edges connecting nodes from one cluster to another cluster
        // TODO: identify which is the sPort and tPort
        { data: { id: 'eanode-9-bnode-9', source: 'anode-9', target: 'bnode-9', sPort: 1, tPort: 1 } },
        { data: { id: 'eanode-8-dnode-9', source: 'anode-8', target: 'dnode-9', sPort: 1, tPort: 1 } },
        { data: { id: 'ebnode-8-dnode-8', source: 'bnode-8', target: 'dnode-8', sPort: 1, tPort: 1 } },

    ];
