// TODO: refactor to for loop
var numberClusterNodes = 22;

dataset = [
        // central switch
        { data: { id: 'centralSwitch', label: 'switch' }, classes: 'switch' },

        // group 1
        { data: { id: 'ispA'}},
        { data: { id: 'a01', label: '172.30.1.1', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a02', label: '172.30.1.2', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a03', label: '172.30.1.3', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a04', label: '172.30.1.4', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a05', label: '172.30.1.5', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a06', label: '172.30.1.6', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a07', label: '172.30.1.7', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a08', label: '172.30.1.8', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a09', label: '172.30.1.9', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a10', label: '172.30.1.10', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a11', label: '172.30.1.11', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a12', label: '172.30.1.12', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a13', label: '172.30.1.13', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a14', label: '172.30.1.14', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a15', label: '172.30.1.15', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a16', label: '172.30.1.16', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a17', label: '172.30.1.17', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a18', label: '172.30.1.18', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a19', label: '172.30.1.19', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a20', label: '172.30.1.20', parent: 'ispA', numPorts: 1}},
        { data: { id: 'a21', label: '172.30.1.21', parent: 'ispA', numPorts: 2}},   // connected to the central switch and its own cluster switch
        { data: { id: 'a22', label: '172.30.1.22', parent: 'ispA', numPorts: 2}},   // connected to the central switch and its own cluster switch
        { data: { id: 'aSwitch', label: 'switch', parent: 'ispA', numPorts: numberClusterNodes}, classes: 'switch'},

        // group 2
        { data: { id: 'ispB'}},
        { data: { id: 'b01', label: '172.30.2.1', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b02', label: '172.30.2.2', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b03', label: '172.30.2.3', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b04', label: '172.30.2.4', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b05', label: '172.30.2.5', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b06', label: '172.30.2.6', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b07', label: '172.30.2.7', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b08', label: '172.30.2.8', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b09', label: '172.30.2.9', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b10', label: '172.30.2.10', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b11', label: '172.30.2.11', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b12', label: '172.30.2.12', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b13', label: '172.30.2.13', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b14', label: '172.30.2.14', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b15', label: '172.30.2.15', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b16', label: '172.30.2.16', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b17', label: '172.30.2.17', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b18', label: '172.30.2.18', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b19', label: '172.30.2.19', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b20', label: '172.30.2.20', parent: 'ispB', numPorts: 1 }},
        { data: { id: 'b21', label: '172.30.2.21', parent: 'ispB', numPorts: 2 }},
        { data: { id: 'b22', label: '172.30.2.22', parent: 'ispB', numPorts: 2 }},
        { data: { id: 'bSwitch', label: 'switch', parent: 'ispB', numPorts: numberClusterNodes }, classes: 'switch' },

        // group 3
        { data: { id: 'ispC'}},
        { data: { id: 'c01', label: '172.30.3.1', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c02', label: '172.30.3.2', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c03', label: '172.30.3.3', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c04', label: '172.30.3.4', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c05', label: '172.30.3.5', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c06', label: '172.30.3.6', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c07', label: '172.30.3.7', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c08', label: '172.30.3.8', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c09', label: '172.30.3.9', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c10', label: '172.30.3.10', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c11', label: '172.30.3.11', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c12', label: '172.30.3.12', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c13', label: '172.30.3.13', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c14', label: '172.30.3.14', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c15', label: '172.30.3.15', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c16', label: '172.30.3.16', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c17', label: '172.30.3.17', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c18', label: '172.30.3.18', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c19', label: '172.30.3.19', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c20', label: '172.30.3.20', parent: 'ispC', numPorts: 1  }},
        { data: { id: 'c21', label: '172.30.3.21', parent: 'ispC', numPorts: 2  }},
        { data: { id: 'c22', label: '172.30.3.22', parent: 'ispC', numPorts: 2  }},
        { data: { id: 'cSwitch', label: 'switch', parent: 'ispC', numPorts: numberClusterNodes }, classes: 'switch' },
        
        // edges for group 1
        { data: { id: 'ea01', source: 'a01', target: 'aSwitch', sPort: 0, tPort: 0 }, classes: 'dashed' },
        { data: { id: 'ea02', source: 'a02', target: 'aSwitch', sPort: 0, tPort: 1 }, classes: 'dashed' },
        { data: { id: 'ea03', source: 'a03', target: 'aSwitch', sPort: 0, tPort: 2 }, classes: 'dashed' },
        { data: { id: 'ea04', source: 'a04', target: 'aSwitch', sPort: 0, tPort: 3 }, classes: 'dashed' },
        { data: { id: 'ea05', source: 'a05', target: 'aSwitch', sPort: 0, tPort: 4 }, classes: 'dashed' },
        { data: { id: 'ea06', source: 'a06', target: 'aSwitch', sPort: 0, tPort: 5 }, classes: 'dashed' },
        { data: { id: 'ea07', source: 'a07', target: 'aSwitch', sPort: 0, tPort: 6 }, classes: 'dashed' },
        { data: { id: 'ea08', source: 'a08', target: 'aSwitch', sPort: 0, tPort: 7 }, classes: 'dashed' },
        { data: { id: 'ea09', source: 'a09', target: 'aSwitch', sPort: 0, tPort: 8 }, classes: 'dashed' },
        { data: { id: 'ea10', source: 'a10', target: 'aSwitch', sPort: 0, tPort: 9 }, classes: 'dashed' },
        { data: { id: 'ea11', source: 'a11', target: 'aSwitch', sPort: 0, tPort: 10 }, classes: 'dashed' },
        { data: { id: 'ea12', source: 'a12', target: 'aSwitch', sPort: 0, tPort: 11 }, classes: 'dashed' },
        { data: { id: 'ea13', source: 'a13', target: 'aSwitch', sPort: 0, tPort: 12 }, classes: 'dashed' },
        { data: { id: 'ea14', source: 'a14', target: 'aSwitch', sPort: 0, tPort: 13 }, classes: 'dashed' },
        { data: { id: 'ea15', source: 'a15', target: 'aSwitch', sPort: 0, tPort: 14 }, classes: 'dashed' },
        { data: { id: 'ea16', source: 'a16', target: 'aSwitch', sPort: 0, tPort: 15 }, classes: 'dashed' },
        { data: { id: 'ea17', source: 'a17', target: 'aSwitch', sPort: 0, tPort: 16 }, classes: 'dashed' },
        { data: { id: 'ea18', source: 'a18', target: 'aSwitch', sPort: 0, tPort: 17 }, classes: 'dashed' },
        { data: { id: 'ea19', source: 'a19', target: 'aSwitch', sPort: 0, tPort: 18 }, classes: 'dashed' },
        { data: { id: 'ea20', source: 'a20', target: 'aSwitch', sPort: 0, tPort: 19 }, classes: 'dashed' },
        { data: { id: 'ea21', source: 'a21', target: 'aSwitch', sPort: 0, tPort: 20 }, classes: 'dashed' },
        { data: { id: 'ea22', source: 'a22', target: 'aSwitch', sPort: 0, tPort: 21 }, classes: 'dashed' },

        // edges for group 2
        { data: { id: 'eb01', source: 'b01', target: 'bSwitch', sPort: 0, tPort: 0 }, classes: 'dashed' },
        { data: { id: 'eb02', source: 'b02', target: 'bSwitch', sPort: 0, tPort: 1 }, classes: 'dashed' },
        { data: { id: 'eb03', source: 'b03', target: 'bSwitch', sPort: 0, tPort: 2 }, classes: 'dashed' },
        { data: { id: 'eb04', source: 'b04', target: 'bSwitch', sPort: 0, tPort: 3 }, classes: 'dashed' },
        { data: { id: 'eb05', source: 'b05', target: 'bSwitch', sPort: 0, tPort: 4 }, classes: 'dashed' },
        { data: { id: 'eb06', source: 'b06', target: 'bSwitch', sPort: 0, tPort: 5 }, classes: 'dashed' },
        { data: { id: 'eb07', source: 'b07', target: 'bSwitch', sPort: 0, tPort: 6 }, classes: 'dashed' },
        { data: { id: 'eb08', source: 'b08', target: 'bSwitch', sPort: 0, tPort: 7 }, classes: 'dashed' },
        { data: { id: 'eb09', source: 'b09', target: 'bSwitch', sPort: 0, tPort: 8 }, classes: 'dashed' },
        { data: { id: 'eb10', source: 'b10', target: 'bSwitch', sPort: 0, tPort: 9 }, classes: 'dashed' },
        { data: { id: 'eb11', source: 'b11', target: 'bSwitch', sPort: 0, tPort: 10 }, classes: 'dashed' },
        { data: { id: 'eb12', source: 'b12', target: 'bSwitch', sPort: 0, tPort: 11 }, classes: 'dashed' },
        { data: { id: 'eb13', source: 'b13', target: 'bSwitch', sPort: 0, tPort: 12 }, classes: 'dashed' },
        { data: { id: 'eb14', source: 'b14', target: 'bSwitch', sPort: 0, tPort: 13 }, classes: 'dashed' },
        { data: { id: 'eb15', source: 'b15', target: 'bSwitch', sPort: 0, tPort: 14 }, classes: 'dashed' },
        { data: { id: 'eb16', source: 'b16', target: 'bSwitch', sPort: 0, tPort: 15 }, classes: 'dashed' },
        { data: { id: 'eb17', source: 'b17', target: 'bSwitch', sPort: 0, tPort: 16 }, classes: 'dashed' },
        { data: { id: 'eb18', source: 'b18', target: 'bSwitch', sPort: 0, tPort: 17 }, classes: 'dashed' },
        { data: { id: 'eb19', source: 'b19', target: 'bSwitch', sPort: 0, tPort: 18 }, classes: 'dashed' },
        { data: { id: 'eb20', source: 'b20', target: 'bSwitch', sPort: 0, tPort: 19 }, classes: 'dashed' },
        { data: { id: 'eb21', source: 'b21', target: 'bSwitch', sPort: 0, tPort: 20 }, classes: 'dashed' },
        { data: { id: 'eb22', source: 'b22', target: 'bSwitch', sPort: 0, tPort: 21 }, classes: 'dashed' },

        // edges for group 3
        { data: { id: 'ec01', source: 'c01', target: 'cSwitch', sPort: 0, tPort: 0 }, classes: 'dashed' },
        { data: { id: 'ec02', source: 'c02', target: 'cSwitch', sPort: 0, tPort: 1 }, classes: 'dashed' },
        { data: { id: 'ec03', source: 'c03', target: 'cSwitch', sPort: 0, tPort: 2 }, classes: 'dashed' },
        { data: { id: 'ec04', source: 'c04', target: 'cSwitch', sPort: 0, tPort: 3 }, classes: 'dashed' },
        { data: { id: 'ec05', source: 'c05', target: 'cSwitch', sPort: 0, tPort: 4 }, classes: 'dashed' },
        { data: { id: 'ec06', source: 'c06', target: 'cSwitch', sPort: 0, tPort: 5 }, classes: 'dashed' },
        { data: { id: 'ec07', source: 'c07', target: 'cSwitch', sPort: 0, tPort: 6 }, classes: 'dashed' },
        { data: { id: 'ec08', source: 'c08', target: 'cSwitch', sPort: 0, tPort: 7 }, classes: 'dashed' },
        { data: { id: 'ec09', source: 'c09', target: 'cSwitch', sPort: 0, tPort: 8 }, classes: 'dashed' },
        { data: { id: 'ec10', source: 'c10', target: 'cSwitch', sPort: 0, tPort: 9 }, classes: 'dashed' },
        { data: { id: 'ec11', source: 'c11', target: 'cSwitch', sPort: 0, tPort: 10 }, classes: 'dashed' },
        { data: { id: 'ec12', source: 'c12', target: 'cSwitch', sPort: 0, tPort: 11 }, classes: 'dashed' },
        { data: { id: 'ec13', source: 'c13', target: 'cSwitch', sPort: 0, tPort: 12 }, classes: 'dashed' },
        { data: { id: 'ec14', source: 'c14', target: 'cSwitch', sPort: 0, tPort: 13 }, classes: 'dashed' },
        { data: { id: 'ec15', source: 'c15', target: 'cSwitch', sPort: 0, tPort: 14 }, classes: 'dashed' },
        { data: { id: 'ec16', source: 'c16', target: 'cSwitch', sPort: 0, tPort: 15 }, classes: 'dashed' },
        { data: { id: 'ec17', source: 'c17', target: 'cSwitch', sPort: 0, tPort: 16 }, classes: 'dashed' },
        { data: { id: 'ec18', source: 'c18', target: 'cSwitch', sPort: 0, tPort: 17 }, classes: 'dashed' },
        { data: { id: 'ec19', source: 'c19', target: 'cSwitch', sPort: 0, tPort: 18 }, classes: 'dashed' },
        { data: { id: 'ec20', source: 'c20', target: 'cSwitch', sPort: 0, tPort: 19 }, classes: 'dashed' },
        { data: { id: 'ec21', source: 'c21', target: 'cSwitch', sPort: 0, tPort: 20 }, classes: 'dashed' },
        { data: { id: 'ec22', source: 'c22', target: 'cSwitch', sPort: 0, tPort: 21 }, classes: 'dashed' },

        // edges connnecting two nodes to central switch
        { data: { id: 'ed01', source: 'a21', target: 'centralSwitch', sPort: 3, tPort: 0 } },
        { data: { id: 'ed02', source: 'a22', target: 'centralSwitch', sPort: 3, tPort: 0 } },
        { data: { id: 'ed03', source: 'b21', target: 'centralSwitch', sPort: 3, tPort: 1 } },
        { data: { id: 'ed04', source: 'b22', target: 'centralSwitch', sPort: 3, tPort: 1 } },
        { data: { id: 'ed05', source: 'c21', target: 'centralSwitch', sPort: 3, tPort: 2 } },
        { data: { id: 'ed06', source: 'c22', target: 'centralSwitch', sPort: 3, tPort: 2 } },

    ];
